development:
  adapter: postgresql
  encoding: unicode
  database: simplewebapp
  pool: 2
  username: dev
  password: dev
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: simplewebapp
  pool: 2
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>